Tution_Media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homeview.as_view(), name='home'),
    path('about/', views.Aboutview.as_view(), name='about'),
    path('service/', views.serviceview.as_view(), name='service'),
    
    path('user/', include('users.urls')),
    path('tution/', include('tution.urls')),
    path('apply/', include('apply_tution.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py


from django.urls import path

from . import views

urlpatterns = [
    path('register/',  views.RegistrationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
    path('contact/', views.Contactview.as_view(), name='contact'),

    path('login/',  views.Userloginviews.as_view(), name='login'),
    path('profile/<str:username>/',  views.profileview, name='profile'),
    path('history/<str:username>/',  views.Tutionhistory, name='history'),
    path('allhistory/<str:username>/',  views.allTutionhistory, name='allhistory'),
    path('logout/',  views.userlogoutview.as_view(), name='logout'),

    path('pass_change/', views.password_change, name='pass_change'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ApplicantModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_no = models.CharField(max_length=12)
    educational_qualification = models.TextField()

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class ContactModel(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.IntegerField()
    comment = models.TextField()

    def __str__(self):
        return self.fullname
    

users/forms.py
# django builtin model forom
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import ApplicantModel, ContactModel

class RegisterForm(UserCreationForm):
    
    # If i want to any fields custom modify
    mobile_no = forms.CharField(max_length=12)
    educational_qualification = forms.CharField(max_length=100)
    
    class Meta:
        model = User
        
        fields = ['username', 'first_name', 'last_name', 'email', 'mobile_no', 'educational_qualification']
        
    def save(self, commit= True):
        user =  super().save(commit=False)
        if commit == True:
            user.is_active = False
            user.save() # user model a data save hobe
             
            print(self.cleaned_data['mobile_no'])
            # UserBankAccountModel model a data save hobe
            ApplicantModel.objects.create(
                user = user,
                mobile_no = self.cleaned_data['mobile_no'],
                educational_qualification = self.cleaned_data['educational_qualification']
            )
            
        return user


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from .models import ApplicantModel
from django.contrib.auth.models import User
from .forms import RegisterForm
from django.views.generic import FormView, DetailView, CreateView
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.views import View
# verify
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
# for email
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.contrib import messages

# Create your views here.
# class UserRegistrationViews(FormView):
#     template_name = 'user_regostration.html'
#     form_class = forms.RegisterForm
#     success_url =reverse_lazy('login')
    
#     def form_valid(self, form):
#         user = form.save()
#         login(self.request, user)
#         return super().form_valid(form)




class RegistrationView(View):
    template_name = 'user_regostration.html'
    form_class = RegisterForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save()

            # Generate token for email validation
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))

            # Build the activation link
            activation_link = reverse('activate', kwargs={'uidb64': uid, 'token': token})
            activation_link = request.build_absolute_uri(activation_link)

            # Send confirmation email
            email_subject = 'Confirm your email'
            email_body = render_to_string('confirm_email.html', {'activation_link': activation_link})

            email = EmailMultiAlternatives(email_subject, '', to=[user.email])
            email.attach_alternative(email_body, "text/html")
            email.send()

            return HttpResponse("Check your email for confirmation.")
        
        return render(request, self.template_name, {'form': form})


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = get_user_model().objects.get(pk=uid)

            if user and default_token_generator.check_token(user, token):
                user.is_active = True
                user.save()
                return HttpResponse("Your account is now activated. You can log in.")
            else:
                return HttpResponse("Activation link is invalid.")
        except Exception as e:
            return HttpResponse("Activation link is invalid.")




class Userloginviews(LoginView):
    template_name = 'user_login.html'
    
    def get_success_url(self):
        if self.request.user.is_active:
            messages.success(self.request, 'Login Successfully. Welcome Back!')
            return reverse_lazy('home')
        else:
            messages.error(self.request, 'Registration first. Then try login')
            return reverse_lazy('register')
    
class userlogoutview(View):
    def get(self, request):
        logout(request)
        messages.success(self.request, 'Logout Successfully. See you later!')
        return redirect('home')


from apply_tution.models import ApplicationModel

@login_required
def profileview(request, username):
    applicant = get_object_or_404(ApplicantModel, user=request.user)
    
    selected_applications = ApplicationModel.objects.filter(applicant=applicant, appaly_status='Selected')
    user = get_object_or_404(User, username=username)
    
    applicant = get_object_or_404(ApplicantModel, user=user)
    print(applicant.mobile_no)
    return render(request, 'profile.html', {'data': applicant, 'application' : selected_applications})

@login_required
def Tutionhistory(request, username):
    applicant = get_object_or_404(ApplicantModel, user=request.user)
    
    selected_applications = ApplicationModel.objects.filter(applicant=applicant, appaly_status='Selected')
    user = get_object_or_404(User, username=username)
    
    applicant = get_object_or_404(ApplicantModel, user=user)
    print(applicant.mobile_no)
    return render(request, 'tution_history.html', {'data': applicant, 'application' : selected_applications})

@login_required
def allTutionhistory(request, username):
    applicant = get_object_or_404(ApplicantModel, user=request.user)
    
    selected_applications = ApplicationModel.objects.filter(applicant=applicant)
    user = get_object_or_404(User, username=username)
    
    applicant = get_object_or_404(ApplicantModel, user=user)
    print(applicant.mobile_no)
    return render(request, 'all_tution_history.html', {'data': applicant, 'application' : selected_applications})


from .models import ContactModel
from .forms import ContactForm
class Contactview(CreateView):
    model = ContactModel
    form_class = ContactForm
    template_name = 'contact.html'

    success_url = reverse_lazy('home')

from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'password update successfully')
            return redirect('home')
        
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'pass_change.html', {'form': form})

users/templates/all_tution_history.html
{% extends "base.html" %}
{% load static %}
{% block title %}History{% endblock title %}

{% block content %}

<div class="bg-body-secondary pb-4">
  <div class="table-responsive">
    {% if application %}
    <h1 class="text-center p-5"> All Applied Tution History</h1>
    <hr>
      <table class="table table-striped table-hover w-100 bg-body-secondary">
          <thead>
              <tr style="padding-left: 50px;">
                  <th style="padding-left: 50px;" scope="col">Tution ID</th>
                  <th scope="col">Apply Time</th>
                  <th scope="col">Subject</th>
                  <th scope="col">Tution Location</th>
                  <th scope="col">Fee</th>
                  <th scope="col">Appaly Status</th>
              </tr>
          </thead>
          <tbody>
              {% for i in application %}
                  <tr>
                      <th style="padding-left: 50px;" scope="row">{{i.tution.id}}</th>
                      <td>{{i.created_time}}</td>
                      <td>{{i.tution.subject}}</td>
                      <td>{{i.tution.location}}</td>
                      <td>{{i.tution.fee}}</td>
                      <td>{{i.appaly_status}}</td>
                      
                  </tr>
              {% endfor %}
          </tbody>
      </table>
      {% else %}
      
      <div class="container text-center mt-5">
        <div>
            <h1>Not found tution history</h1>
        </div>

        <div>
            <img style="mix-blend-mode: color-burn;" src="{% static "opps.jpg" %}" alt="opps">
        </div>
    </div>
      {% endif %}
  </div>
</div>

{% endblock content %}

users/templates/confirm_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Confirmation</title>
</head>
<body>
    <p>Click the link below to activate your account:</p>
    <p><a href="{{ activation_link }}">{{ activation_link }}</a></p>
</body>
</html>

users/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Contact{% endblock title %}
{% block content %}


<head>
    <style>
        label{
            color: blue;
            font-weight: bold;

        }
        #id_fullname{
            background-color: rgb(246, 250, 250);
            padding: 5px;
            border-radius: 30px;  
        }
        #id_fullname:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_email{
            background-color: rgb(246, 250, 250);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_email:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_phone{
            background-color: rgb(246, 250, 250);
            padding: 10px;
            border-radius: 30px;  
        }
        #id_phone:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_comment{
            background-color: rgb(246, 250, 250);
            height: 150px;
            padding: 10px;
            border-radius: 30px;  
        }
        #id_comment:hover{
            background-color: rgb(252, 249, 249);
        }
    </style>
</head>


<div style=" background:white; border-radius: 50px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container pt-3 pb-3  mt-4 mb-4">
    <h3 class="text-center">Contact</h3>
    <hr>
    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="col-md-7 col-sm-12">
            <img class="img-fluid " src="{% static 'contact.webp' %}" alt="Register">
          </div>
          <div class="col-md-5 col-sm-12">
            <div style=" margin: auto;">
                <form method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            
        
          </div>
    </div>
    
    
</div>


{% endblock content %}

users/templates/pass_change.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}pass change{% endblock title %}


{% block content %}



<div style="border-radius: 50px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container pt-3 pb-3  mt-4 mb-4">
    <h3 class="text-center">Password Change</h3>
    <hr>
    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="col-md-7 col-sm-12">
            <img style="" class="img-fluid " src="{% static 'login.jpg' %}" alt="Register">
          </div>
          <div class="col-md-5 col-sm-12">
            <div style=" margin: auto;">
                <form method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            
        
        </div>
    </div>
</div>


{% endblock content %}

users/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile{% endblock title %}

{% block content %}
<div class="container mt-4 ">


  <section class="vh-100" style="background-color: #f4f5f7;">
    <div class=" py-3 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-8 col-lg-8 mb-4 mb-lg-0">
          <div class="card mb-3 " style="border-radius: .5rem;">
            <div class="row g-0">
              <div class="col-md-4 text-center pt-5 pb-5"
                style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;
                background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 0%, rgba(165,238,253,1) 0%, rgba(236,235,227,1) 46%, rgba(86,204,229,1) 96%);

                
                ">
                <img src="{% static 'profile.webp' %}"
                  alt="Avatar" class="img-fluid my-5" style="width: 200px; border-radius: 100px;" />
                <h5 class="text-dark">{{data.user.first_name}} {{data.user.last_name}}</h5>
                <p class="text-dark">{{data.educational_qualification}}</p>
         
              </div>
              <div class="col-md-8 pt-5">
                <div class="card-body p-4">
                  <h6>Information</h6>
                  <hr class="mt-0 mb-4">
                  <div class="row pt-1">
                    <div class="col-6 mb-3">
                      <h6>Email</h6>
                      <p class="text-muted">{{data.user.email}}</p>
                    </div>
                    <div class="col-6 mb-3">
                      <h6>Phone</h6>
                      <p class="text-muted">{{data.mobile_no}}</p>
                    </div>
                  </div>
                  <!-- <h6>Projects</h6>
                  <hr class="mt-0 mb-4">
                  <div class="row pt-1">
                    <div class="col-6 mb-3">
                      <h6>Recent</h6>
                      <p class="text-muted">Lorem ipsum</p>
                    </div>
                    <div class="col-6 mb-3">
                      <h6>Most Viewed</h6>
                      <p class="text-muted">Dolor sit amet</p>
                    </div>
                  </div> -->
                  <!-- <div class="d-flex justify-content-start">
                    <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                    <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                    <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                  </div> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>





<!-- 
    <div class="row d-flex justify-content-center align-items-center mt-5" >
      <div style="text-align: center;" class="col">
        <img style="width: 75%; height: auto; " src="{% static 'profile.webp' %}" alt="patient">
        <h5  class="m-4">{{user.username}}</h5>
      </div>
      <div class="col"> 
        <p style="text-align: center;">Name - {{data.user.first_name}} {{data.user.last_name}}</p>
        <p style="text-align: center;">Email - {{data.user.email}}</p>
        <p style="text-align: center;">Phone Number - {{data.mobile_no}}</p>
        <p style="text-align: center;">Educational Qualification - {{data.educational_qualification}}</p>

      </div>
    </div> -->
  </div>
    
<div class="mt-5">
  <hr>
</div>

<div class="bg-body-secondary pb-4">
  <h1 class="text-center p-5">Tution History</h1>
  <div class="table-responsive">
      <table class="table table-striped table-hover w-100 bg-body-secondary">
          <thead>
              <tr style="padding-left: 50px;">
                  <th style="padding-left: 50px;" scope="col">Tution ID</th>
                  <th scope="col">Apply Time</th>
                  <th scope="col">Subject</th>
                  <th scope="col">Tution Location</th>
                  <th scope="col">Fee</th>
                  <th scope="col">Action</th>
              </tr>
          </thead>
          <tbody>
              {% for i in application %}
                  <tr>
                      <th style="padding-left: 50px;" scope="row">{{i.tution.id}}</th>
                      <td>{{i.created_time}}</td>
                      <td>{{i.tution.subject}}</td>
                      <td>{{i.tution.location}}</td>
                      <td>{{i.tution.fee}}</td>
                      <td><a class="btn btn-info" href="{% url 'review' i.tution.id %}">Reviews </a></td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
</div>

{% endblock content %}

users/templates/tution_history.html
{% extends "base.html" %}
{% load static %}
{% block title %}History{% endblock title %}

{% block content %}

<div class="bg-body-secondary pb-4">
  <h1 class="text-center p-5">Tution History</h1>
  <div class="table-responsive">
    {% if application %}
      <table class="table table-striped table-hover w-100 bg-body-secondary">
          <thead>
              <tr style="padding-left: 50px;">
                  <th style="padding-left: 50px;" scope="col">Tution ID</th>
                  <th scope="col">Apply Time</th>
                  <th scope="col">Subject</th>
                  <th scope="col">Tution Location</th>
                  <th scope="col">Fee</th>
                  <th scope="col">Action</th>
              </tr>
          </thead>
          <tbody>
              {% for i in application %}
                  <tr>
                      <th style="padding-left: 50px;" scope="row">{{i.tution.id}}</th>
                      <td>{{i.created_time}}</td>
                      <td>{{i.tution.subject}}</td>
                      <td>{{i.tution.location}}</td>
                      <td>{{i.tution.fee}}</td>
                      <td><a class="btn btn-info" href="{% url 'review' i.tution.id %}">Reviews </a></td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
      {% else %}
      
      <div class="container text-center mt-5">
        <div>
            <h1>Not found tution history</h1>
        </div>

        <div>
            <img style="mix-blend-mode: color-burn;" src="{% static "opps.jpg" %}" alt="opps">
        </div>
    </div>
      {% endif %}
  </div>
</div>

{% endblock content %}

users/templates/user_login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock title %}


{% block content %}

<head>
    <style>
        #id_username{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;  
        }
        #id_username:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_password{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_password:hover{
            background-color: rgb(252, 249, 249);
        }
    </style>
</head>


<div style=" background:white; border-radius: 50px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container  pt-3 pb-3  mt-4 mb-4">
    <h3 class="text-center">Login</h3>
    <hr>
    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="col-md-7 col-sm-12">
            <img style="" class="img-fluid " src="{% static 'login.jpg' %}" alt="Register">
          </div>
          <div class="col-md-5 col-sm-12">
            <div style=" margin: auto;">
                <form method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
            
        
        </div>
    </div>
</div>


{% endblock content %}

users/templates/user_regostration.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Registration{% endblock title %}
{% block content %}


<head>
    <style>
        #id_username{
            background-color: rgb(231, 235, 235);
            padding: 5px;
            border-radius: 30px;  
        }
        #id_username:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_first_name{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_first_name:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_last_name{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;  
        }
        #id_last_name:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_email{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_email:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_mobile_no{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;  
        }
        #id_mobile_no:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_educational_qualification{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_educational_qualification:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_password1{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_password1:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_password2{
            background-color: rgb(231, 235, 235);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_password2:hover{
            background-color: rgb(252, 249, 249);
        }
    </style>
</head>


<div style="border-radius: 50px; background:white; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container pt-3 pb-3 mt-4 mb-4">
    <h3 class="text-center">Registration</h3>
    <hr>
    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="col-md-7 col-sm-12">
            <img  class="img-fluid " src="{% static 'reg.png' %}" alt="Register">
            <br>
            <p class="text-center">Have an Account? <a href="{% url 'login' %}"> Login Here</a> </p>
          </div>
          <div class="col-md-5 col-sm-12">
            <div style=" margin: auto;">
                <form method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Signup</button>
                </form>
            </div>
            
        
          </div>
    </div>
    
    
</div>


{% endblock content %}