Tution_Media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homeview.as_view(), name='home'),
    path('about/', views.Aboutview.as_view(), name='about'),
    path('service/', views.serviceview.as_view(), name='service'),
    
    path('user/', include('users.urls')),
    path('tution/', include('tution.urls')),
    path('apply/', include('apply_tution.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tution/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('add/', views.AddTution.as_view(), name='add_tution'),
    path('teachers/', views.seeTeacher, name='teachers'),
    path('seeTution/',  views.seeTution, name='seeTution'),
    path('class/<slug:class_slug>/', views.seeTution, name='class_slug'),
    path('edit/<int:pk>/', views.EditTutionView.as_view(), name='edit_tution'),
    path('delete/<int:id>/', views.delete_tution, name='delete_tution'),
    path('review/<int:tution_id>/', views.review_view, name='review'),
    path('reviews/<int:tution_id>/', views.tution_reviews_view, name='tution_reviews'),


    
]

users/urls.py


from django.urls import path

from . import views

urlpatterns = [
    path('register/',  views.RegistrationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
    path('contact/', views.Contactview.as_view(), name='contact'),

    path('login/',  views.Userloginviews.as_view(), name='login'),
    path('profile/<str:username>/',  views.profileview, name='profile'),
    path('history/<str:username>/',  views.Tutionhistory, name='history'),
    path('allhistory/<str:username>/',  views.allTutionhistory, name='allhistory'),
    path('logout/',  views.userlogoutview.as_view(), name='logout'),

    path('pass_change/', views.password_change, name='pass_change'),

]

tution/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import ApplicantModel
# Create your models here.


class TutionClassModel(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

TUTION_STATUS = [
    ('Running', 'Running'),
    ('Completed', 'Completed'),
]

class TutionModel(models.Model):
    tutionclass = models.ManyToManyField(TutionClassModel)
    subject = models.CharField(max_length=100)
    weekly_day = models.IntegerField()
    daily_time = models.IntegerField()
    location = models.CharField(max_length=200)
    fee = models.IntegerField()
    tution_status = models.CharField(max_length=30, choices=TUTION_STATUS, default='Running')

STAR_CHOICE = [
    ('⭐', '⭐'),
    ('⭐⭐', '⭐⭐'),
    ('⭐⭐⭐', '⭐⭐⭐'),
    ('⭐⭐⭐⭐', '⭐⭐⭐⭐'),
    ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'),
]

class ReviewModel(models.Model):
    reviewer = models.ForeignKey(ApplicantModel, on_delete=models.CASCADE)
    tution = models.ForeignKey(TutionModel, on_delete=models.CASCADE)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    ratting = models.CharField(max_length=100, choices = STAR_CHOICE)


    def __str__(self):
        return f"{self.reviewer.user.first_name} to {self.tution.subject}"
    

class TeacherModel(models.Model):
    image = models.ImageField(upload_to='tution/images/', blank = True,null = True)
    code = models.IntegerField()
    fullname = models.CharField(max_length=100)
    university = models.CharField(max_length=150)
    sub = models.CharField(max_length=150)
    ex_location = models.CharField(max_length=150)
    ex_class= models.CharField(max_length=150)
    living_place = models.CharField(max_length=150)
    ex_salary = models.IntegerField()

    def __str__(self):
        return self.fullname
    

tution/forms.py
from django import forms
from .models import TutionModel, ReviewModel

class TutionForm(forms.ModelForm):
    class Meta:
        model = TutionModel
        fields = ['tutionclass', 'subject', 'weekly_day', 'daily_time', 'location', 'fee']

class EditTutionForm(forms.ModelForm):
    class Meta:
        model = TutionModel
        fields = '__all__'

class ReviewForm(forms.ModelForm):
       
    class Meta:
        model = ReviewModel
        fields = ['body', 'ratting']
        
       

tution/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models
from . import forms
from django.contrib.auth.decorators import user_passes_test

from django.contrib.auth.decorators import login_required
# Create your views here.

class AddTution(CreateView):
    model = models.TutionModel
    form_class = forms.TutionForm
    template_name = 'add_tution.html'

    success_url = reverse_lazy('add_tution')

@login_required
def seeTution(request, class_slug = None):
    data = models.TutionModel.objects.all()
    if class_slug is not None:
        tutionclass = models.TutionClassModel.objects.get(slug = class_slug)
        data = models.TutionModel.objects.filter(tutionclass = tutionclass)
        
    tutionclass = models.TutionClassModel.objects.all()
    # print(data[::-1])
    return render(request, 'seeTution.html', {'data':data[::-1], 'tutionclass': tutionclass})

def seeTeacher(request):
    data = models.TeacherModel.objects.all()
    return render(request, 'teachers.html', {'data':data})

class EditTutionView(UpdateView):
    model = models.TutionModel
    form_class = forms.EditTutionForm
    template_name = 'edit_tution.html'
    success_url = reverse_lazy('seeTution') 

@user_passes_test(lambda u: u.is_superuser)
def delete_tution(request, id):
    record = models.TutionModel.objects.get(pk=id)
    record.delete()
    return redirect('seeTution')



@login_required
def review_view(request, tution_id):
    tution = get_object_or_404(models.TutionModel, pk=tution_id)
    
    if request.method == 'POST':
        form = forms.ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.reviewer = request.user.applicantmodel
            review.tution = tution
            review.save()
            return redirect('seeTution')  
    else:
        form = forms.ReviewForm()

    return render(request, 'review.html', {'form': form, 'tution': tution})

from .models import TutionModel, ReviewModel
@login_required
def tution_reviews_view(request, tution_id):
    tution = get_object_or_404(TutionModel, pk=tution_id)
    reviews = ReviewModel.objects.filter(tution=tution)

    return render(request, 'display_review.html', {'tution': tution, 'reviews': reviews})

tution/templates/add_tution.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add{% endblock title %}

{% block content %}

<head>
    <style>
        #id_tutionclass{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 20px;  
        }
        #id_tutionclass:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_subject{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_subject:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_weekly_day{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_weekly_day:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_daily_time{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_daily_time:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_location{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_location:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_fee{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_fee:hover{
            background-color: rgb(252, 249, 249);
        }
    </style>
</head>

<div  style=" border-radius: 50px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container  col-md-4  pt-3 pb-3 bg-dark-subtle mt-4 mb-4">

    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="text-center">
            <img style="mix-blend-mode: color-burn; width: 150px;" class="img-fluid " src="{% static 'logicon.jpg' %}" alt="Login icon">
            <h3 class="text-center">Add</h3>
            <hr>
          </div>
          <div class="">
            <div class="pb-md-5" style=" margin: auto;">
                <form class="ps-md-3 pe-md-3" method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
            
        
          </div>
    </div>
    
    
</div>

{% endblock content %}

tution/templates/delete.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="static/style1.css">
</head>
  <body>
    <h1>Hello, world!</h1>


    <div class="footer_area">
        <div class="container">

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

tution/templates/display_review.html
{% extends "base.html" %}

{% block title %}review page{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container pb-5 mt-5" style="width: 50%; margin: auto">
    <h2>Reviews for #{{tution.id}} {{ tution.subject }}</h2>
    {% if reviews %}
        <ul>
            {% for review in reviews %}
                <li>
                    <p>Reviewer: {{ review.reviewer.user.first_name }}  {{ review.ratting }}</p>
                    <p>{{ review.body }}</p>
                    <p> {{ review.created_time }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No reviews for {{ tution.subject }} yet.</p>
    {% endif %}
</div>
{% endblock content %}

tution/templates/edit_tution.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edit{% endblock title %}

{% block content %}

<head>
    <style>
        #id_tutionclass{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 20px;  
        }
        #id_tutionclass:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_subject{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_subject:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_weekly_day{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_weekly_day:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_daily_time{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_daily_time:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_location{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_location:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_fee{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_tution_status:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_tution_status{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_fee:hover{
            background-color: rgb(252, 249, 249);
        }
    </style>
</head>


<div  style=" border-radius: 50px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container  col-md-4  pt-3 pb-3 bg-dark-subtle mt-4 mb-4">

    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="text-center">
            <img style="mix-blend-mode: color-burn; width: 150px;" class="img-fluid " src="{% static 'logicon.jpg' %}" alt="Login icon">
            <h3 class="text-center">Edit</h3>
            <hr>
          </div>
          <div class="">
            <div class="pb-md-5" style=" margin: auto;">
                <form class="ps-md-3 pe-md-3" method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Edit</button>
                </form>
            </div>
            
        
          </div>
    </div>
    
    
</div>

{% endblock content %}

tution/templates/review.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Review{% endblock title %}

{% block content %}

<head>
    <style>
        #id_body{
            background-color: rgb(188, 192, 192);
            height: 150px;
            padding: 10px;
            border-radius: 30px;  
        }
        #id_body:hover{
            background-color: rgb(252, 249, 249);
        }
        #id_ratting{
            background-color: rgb(188, 192, 192);
            padding: 10px;
            border-radius: 30px;
            
        }
        #id_ratting:hover{
            background-color: rgb(252, 249, 249);
        }
    </style>
</head>


<div  style=" border-radius: 50px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="container  col-md-4  pt-3 pb-3 bg-dark-subtle mt-4 mb-4">

    <div class="row d-flex justify-content-center align-items-center mt-2">
        <div class="text-center">
            <img style="mix-blend-mode: color-burn; width: 150px;" class="img-fluid " src="{% static 'review.jpg' %}" alt="Login icon">
            <h3 class="text-center">Comment</h3>
            <hr>
          </div>
          <div class="">
            <div class="pb-md-5" style=" margin: auto;">
                <form class="ps-md-3 pe-md-3" method="post" novalidate>
                    <!-- {{form | crispy}} -->
                    {% csrf_token %}
            
                    <!-- if unauthorize user try for login show a error message -->
                    {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                        <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                    {% endif %}
            
            
                    {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  
                    {% endfor %}
                    <br>
                    <button style="width: 100%; padding: 10px; border-radius: 30px;" type="submit" class="btn btn-primary">Comment</button>
                </form>
            </div>
            
        
          </div>
    </div>
    
    
</div>

{% endblock content %}

tution/templates/seeTution.html
{% extends "base.html" %}
{% load static %}

{% block title %}tution page{% endblock title %}

{% block content %}

<div class="container text-center">
    <a  class="btn btn-primary m-4" href="{% url 'seeTution' %}">ALL</a>
    {% for i in tutionclass %}
 
        <a href="{% url 'class_slug' i.slug %}" class="btn btn-primary m-4">{{i.name}}</a>

    {% endfor %}
</div> 

<div class="container mb-5">
        <button class="px-5 py-2 mb-4 btn btn-success text-white">{{data | length}} result found</button>
        <div class="row  justify-content-center  gap-4">
            {% for i in data %}
            <div class="card border border-primary p-3" style="width: 18rem; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
                <div class="card-header">
                  <h3>Tution ID #{{i.id}}</h3>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Class || 
                    {% for se in i.tutionclass.all %}
                        {{se}}
                    {% endfor %}
                  </li>
                  <li class="list-group-item">Subject || {{i.subject}}</li>
                  <li class="list-group-item">Weekly {{i.weekly_day}} days {{i.daily_time}} Hour</li>
                  <li class="list-group-item">Location || {{i.location}} </li>
                  <li class="list-group-item">Mounthly Fee {{i.fee}}TK</li>
                  {% if i.tution_status == "Running"%}
                  <li class="list-group-item">Tution Status  <button class="btn btn-info">{{i.tution_status}}</button></li>
                  {% else %}
                  <li class="list-group-item">Tution Status  <button class="btn btn-danger">{{i.tution_status}}</button></li>
                  {% endif %}
                  
                  {% if request.user.is_superuser %}
                  <li class="list-group-item text-center">
                    
                    <a class="btn btn-success" href="{% url 'application' i.id %}">Application</a>
                    <a class="btn btn-success" href="{% url 'edit_tution' i.id %}">Edit</a>
                  </li>
                  <li class="list-group-item text-center">
                    <a class="btn btn-danger" href="{% url 'delete_tution' i.id %}">Delete</a>
                  </li>
                  <li class="list-group-item text-center">
                    <a class="btn btn-success" href="{% url 'tution_reviews' i.id %}">View Review</a>
                    </li>
                  {% else %}
                  <li class="list-group-item text-center">
                  <a class="btn btn-success" href="{% url 'tution_reviews' i.id %}">View Review</a>
                  </li>
                  <li class="list-group-item text-center">
                  <a class="btn btn-success" href="{% url 'apply_tution' i.id %}">Apply Heare</a>
                  </li>
                {% endif %}

                </ul>
              </div>
            {% endfor %}
                
        </div>
    </div>
    

</div>



{% endblock content %}

tution/templates/teachers.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Teachers{% endblock title %}

{% block content %}



<div class="container">
    <div class="mb-5">
        <br>
        <h5>Most Active <strong>10</strong> Teachers</h5>
    </div>
    {% for i in data %}
        <div class="card mb-3 mt-5" >
            <div class="row g-3">
                <div class="col-md-4">
                    <img src="{{i.image.url}}" class="img-fluid rounded-start h-100" alt="...">
                </div>

                <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{i.fullname}}</h5>
                    <h5><b>{{i.university}}</b>({{i.sub}})</h5>
                    <br>
                    <br>
                    <p>Expected Location : {{i.ex_location}}</p>
                    <p> Expected Class(s): {{i.ex_class}}</p>

                        <p class="card-text"> <ul class="details list-unstyled cols-2 d-flex gap-5">
                        <li>Living Place :
                            <i class="fa fa-map-marker"> </i><span>  {{i.living_place}}</span>
                        </li>
                        <li>
                            <i class="fa-solid fa-money-bill"></i><span>Expected Salary : {{i.ex_salary}}</span>
                        </li>
                    </ul></p>
                    </div>
                </div>
                        
                        
            </div>
        </div>
               
    {% endfor %}
            
</div>
  


{% endblock content %}